---
title: "index"
author: "joseedquen"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## dise침os experimentales

## DCA

Dosis (4) de fertilizacion nitrogenada:

-   0
-   50
-   100
-   150

```{r}

# Instalar el paquete agricolae si no lo tienes
install.packages("agricolae")

# Cargar el paquete agricolae
library(agricolae)

# Definir los tratamientos (niveles de fertilizaci칩n)
fertilizacion <- c(0, 50, 100, 150)

# Definir las repeticiones
repeticiones <- 5

# Crear el dise침o completamente al azar
dca <- design.crd(trt=fertilizacion, r=repeticiones, seed=123)

# Ver el dise침o generado
print(dca)




```

## DBCA

Factor 1 (dosis nitrogeno):0, 50, 100, 150 Factor 2 (variedades de papa): chanchan y peruanita Bloques: 5

```{r}
dosis <- c(0, 50, 100, 150)
variedad <- c("canchan", "peruanita")

ds <- agricolae::design.ab()

trt<-c(4,2) # factorial 4x2
outdesign <-design.ab(trt =trt, r=5)


str(outdesign)


book<-outdesign$book
book




# analisis de datos
```

```{r}
library(tidyverse)
library(googlesheets4)

```

##importar datos

```{r}
url<-"https://docs.google.com/spreadsheets/d/15r7ZwcZZHbEgltlF6gSFvCTFA-CFzVBWwg3mFlRyKPs/edit?gid=172957346#gid=172957346"

gs<- as_sheets_id(url)

fb<-range_read(gs,"fb")


str(fb)
```

## modelo estadistico

```{r}
modelo<-aov(formula = lfa ~ riego + geno+ riego*geno+ block, data = fb)

plot (modelo)
anova(modelo)
```

##Comparacion de medias

```{r}
library(agricolae)

mc<- agricolae::duncan.test(y = modelo
                            , trt = c("riego", "geno"))


mc

str(mc)


```

```{r}
library(emmeans)
library(multcomp)
library(tidyverse)

mc <- emmeans(modelo, ~ riego/ geno) %>%
  cld(letters = letters, revesed = T)


mc
```

## grafico

```{r}
library(inti)

plot_smr(data = mc
         , type = "bar"
         , x = "geno"
         , y = "emmean"
         , group = "riego"
         , sig = ".group"
         , error = "SE"
         , ylimits = c(0,12000, 2000)
         )
           
```

```{r}
ggplot(mc, aes(x = geno, y = emmean, fill = riego)) +
  geom_bar(stat="identity") + 
  the_minimal() +
  labs(title = "grafico de barras", x = "categoria", y = "valores")


```
